kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linode-block-storage
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linodebs.csi.linode.com